# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Quinnie Rodman
# Description of the Site
description: Actress. Singer. Educator.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/QuinnieRodman/QuinnieRodman.github.io/master/assets/images/actiong.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero.jpg?raw=true

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: RodmanQuinnE@sau.edu
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: quinnerodman@gmail.com
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Quinnie Rodman
# URL for the Image of the Author
author-image: https://github.com/QuinnieRodman/QuinnieRodman.github.io/blob/master/assets/images/Headshot%20(smile)-%20Quinnie%20Rodman.jpg?raw=true
# 60 Words About the Author
author-about: My name is Quinnie Rodman and I am a midwest based actress, singer, and educator from Mount Vernon, IA. I am currently in the process of getting my BA in vocal music education from St. Ambrose University in Davenport, IA expected to graduate in the Spring of 2023. I have been involved in various productions throughout my time at St. Ambrose as well as the professional scene at St. Croix Festival Theater in St. Croix Falls, WI. I love contributing my theatrical efforts on stage and backstage as well as teaching students in the arts. I love to sing, act, work with students, and watch reality TV with my cat. I believe that my music education background gives me a unique perspective on theater that makes me appreciate its educational value and want to work to keep the magic of theater alive for generations to come!
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
